# Generated by Django 6.0.2 on 2026-03-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0005_item_is_surrendered_to_osa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Documents', 'Documents'), ('Personal Effects', 'Personal Belongings'), ('Others', 'Others')], max_length=50),
        ),
    ]
